import express from 'express';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import router_login from './routers/login.js';
import router_new_hack from './routers/new-hack.js';
import router_search from './routers/search.js';
import router_user_infs from './routers/user_infs.js';
import router_hacks_infs from './routers/hacks_infs.js';
import cors from 'cors';
import process from 'process';
dotenv.config();
const dirfile = fileURLToPath(import.meta.url);
const dirname = path.dirname(dirfile);
const server = express();
server.use('/icon', express.static(path.resolve(dirname, 'files', 'icon')));
server.use('/cover', express.static(path.resolve(dirname, 'files', 'cover')));
server.use('/game', express.static(path.resolve(dirname, 'files', 'game_file')));
server.use(cors());
server.use(router_login, router_new_hack, router_search, router_user_infs, router_hacks_infs);
server.listen(process.env.port);
export default server;
